// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wioftjejmipvdivvdraz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpb2Z0amVqbWlwdmRpdnZkcmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDI3NjIsImV4cCI6MjA2NTAxODc2Mn0.nqr0iXD0rwbFYJ0d3_r4hVNpgAfQoVLSR6YQUELp7lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);